### ISSUE TITLE
Wetware circuit cost

### ISSUE THREAD

**Issue by hjae78** [Gregicality/gregicality#15]
As pointed out by Shattered in the discord the first wetware circuit currently only takes LuV power. There are also concerns about the ability to make it using Crystal SMD components. Shattered also raised concerns about the cost of the wetware board.

**Comment by Shattered2909** [comment]
wetware circuits should all take 122880 EU/t (except the mainframe which takes 300000 because its MAX which is fine)

only the first circuit is made in a circuit assembler, rest is assline (good)

the main point here is the circuit board for wetwares which requires a lot of lower tier ones (okay) but the bio aspect is a complete joke. stemcells from extracting eggs and growth medium which is basically meat and salt. this needs some big changes and i honestly dont know how to implement them atm. take a look at GTNH wetware/bio i guess. in my pack i can do some weird shit with botania and blood magic but its not a solution for this mod.
