### ISSUE TITLE
Rework nuclear waste reprocessing

### ISSUE THREAD

**Issue by hjae78** [Gregicality/gregicality#154]

**Comment by Shattered2909** [comment]
Okay, so here is my idea:

Each Fission Fuel should output it's own Nuclear Waste so they drop different things.
Hjae mentioned the idea of adding a Multiblock to process Waste, maybe one that can also be used as a Decay Chamber (modes like the Multiblock Bending/Pressing Machine)

Then we  can have different tiers of waste that require different voltages to process:
MV Machine for Thorium and Uranium Waste
HV for Neptunium and Plutonium
EV for Americium and Curium
IV for Berkelium and Californium
LuV for Einsteinium and Fermium
ZPM for Mendelevium

These should output different resources so players cannot just make Iridium from Thorium (byproduct of Coal Ore)
They should probably all give a little bit of Radon and other Gases but it would make sense to have tiered outputs so Thorium Waste only outputs resources like Copper and Cobalt, Uranium Waste outputs a few more elements plus Thorium ones so the pool grows for higher tier Waste.

To be fair I don't know if I really like this idea in general, Nuclear Reactors outputting all elements, that is either too small to make a difference or very powerful and going to  compete with actual Ores and be broken. But I guess it makes sense because it is realistic.

Always remember that a lot of these resource drops are destroying Fusion as it is right now, it definitely needs a Rework and probably more recipes.

**Comment by Shattered2909** [comment]
Maybe there should also be Ores for some of the higher tier Fuels?

**Comment by Zalgo239** [comment]
Regarding the Gregicality waste I have three ideas to make it more interesting

1:
As you go up in the transuranic element chains the probability of getting an atom to fission gets higher. So higher end fuels should be producing more waste compared to the basic ones, right now they all have a 50% chance, I suggest having the last one always produce waste and making the other give exponentially lower amounts, so:
    Md -> 100%
    Fm -> 75%
    Es -> 56.25%
    Cf -> 42.1875%
    Bk -> 31.640625%
    Cm -> 23.73046875%
    Am -> 17.7978515625%
    Pu -> 13.348388671875%
    Np -> 10.01129150390625%
    U -> 0.75084686279296875%
    Th -> 0.05631351470947265625%
This way each fuel gives you 75% less than the next, round up to the nearest integer to avoid cancer

2:
Fission products shouldn't be immediately extractable, the waste should damage the player in a similar way to hot ingots. They should first spend time in a special machine to decay for a bit

3:
The extraction process could be done chemically rather than via centrifuge


I agree on having some of the fuels/products gated to higher voltage tiers
I don't think that we should have ores for the higher end fuels spawn naturally, those elements have a short half life so they wouldn't be found on a four billion year old planet

**Comment by whatsapp2** [comment]
![Purex](https://user-images.githubusercontent.com/25994176/93373169-9623fb00-f81a-11ea-9f88-da3b15fadcdc.png)
