### ISSUE TITLE
New fusion chains, triple alpha process, nucleosysnthesis and the CNO cycle

### ISSUE THREAD

**Issue by Zalgo239** [Gregicality/gregicality#204]
I made a diagram for the implementation of more fusion chains which happen in real stars
![Fusion(1)](https://user-images.githubusercontent.com/67443118/94518408-26eed380-022a-11eb-99ed-0e1527e9114a.png)

**Comment by warjort** [comment]
You know that at least from the silicon burning these reactions only take place in a collapsing massive star as it goes nova.

It seems very unlikely they could be stabilised in a fusion reactor? We have enough trouble with hydrogen in real life. 

But if it could be stabilised, it would be a legit way of producing neutronium as a waste product! Because that's what produced at the centre of the star during the collapse.

**Comment by Zalgo239** [comment]
The alpha ladder doesn't stop at Si, stars can get up to the Fe group before the breaking of equilibrium which causes the collapse,
you can find more info on stellar nucleosynthesis [here](https://journals.aps.org/rmp/pdf/10.1103/RevModPhys.29.547)

It is true that getting the required conditions to produce a significant amount of these elements is difficult, however the mod (and any mod really) already ignores many requirements that would make a lot of processes much more difficult. In the end it doesn't have to be completely realistic, it has to be fun and make some sense

**Comment by basdxz** [comment]
You have earned my undying respect good sir, but I think we're gonna need a bigger Tokamak ;p

**Comment by pablocnvs** [comment]
done
