### ISSUE TITLE
Conflicted Recipes

### ISSUE THREAD

**Issue by YoungGT** [Gregicality/gregicality#371]
These recipes are conflicted and need circuits to be differentiated.
Dichlorobenzene and Chlorobenzene

![20210218222131](https://user-images.githubusercontent.com/30253037/108370595-cf342180-7237-11eb-842a-22bc90fc35dd.png)
![20210218222154](https://user-images.githubusercontent.com/30253037/108370605-d0fde500-7237-11eb-9fa3-c18d7531bd7c.png)

Soild Steel Machine Casing and Steel Matel Casing
![20210218222355](https://user-images.githubusercontent.com/30253037/108370811-01de1a00-7238-11eb-8f0d-1bf6446d7081.png)

**Comment by DStrand1** [comment]
- For issue 1 (Chlorobenzene):
One of these two recipes is a GTCE recipe, which currently has a PR open to change it. The conflict would still be there, but I would rather wait until that is merged and released to fix it, since it would require removing the GTCE recipe to add a circuit.

- For issue 2 (casings):
The first has a circuit present, does it just ignore the circuit and always do the second recipe instead?

**Comment by TechLord22** [comment]
Fixed in #388.
