### ISSUE TITLE
4,8,16,etc Amps In/output Hatchs are not craftable

### ISSUE THREAD

**Issue by RTL135** [Gregicality/gregicality#517]
Today after I updated to the newiest version (0.22.5) and I found out those hatchs are no longer obtainable, is it a bug or the mod is missing the recipes?

**Comment by RTL135** [comment]
Therefore, the large transformer is also not obtainable.

**Comment by galyfray** [comment]
I check and the recipes seems to be correct in the code they are created using `registerMachineRecipe` this part of the code should be executed 

concerning the transformer part it seems that only the MV 4 and 8 amps recipes are not regitered correctly

**Comment by RTL135** [comment]
I don't know why what is causing this problem, but both trying to craft them and finding recipes by JEI are not give an answer xD. Maybe mods confict? or some sort of settings in config?

**Comment by DStrand1** [comment]
> I check and the recipes seems to be correct in the code they are created using `registerMachineRecipe` this part of the code should be executed

I haven't had the chance to properly look into this yet, but those previously were being added via standard loops and I created a method capable of adding recipes for them. I suspect there is something strange happening with the Objects passed in, since I believe the Crafting Table recipe adder in `ModHandler` in GTCE doesn't really care what is passed into it, and will just fail to add if the recipe is done poorly. This is probably an easy fix, but again I haven't had the chance to address it.
